In [1]:
import sys
sys.path.append("../src")

import pandas as pd
from city_mapping import canonical_city, GREIX_NATIONAL

In [5]:
df = pd.read_excel("../data/raw/greix/City_metrics_public.xlsx", sheet_name = "Tabelle1")
df.head(10)

,Year,Quarter,Month,City,Index,AVG_PRICE_SQM,MED_PRICE_SQM,P75_PRICE_SQM,P25_PRICE_SQM,Inflation_adjusted,TOM_4Q,Closed_one_week_4Q
0,2012,1.0,1.0,Aachen,89.227844,7.10,6.86,8.33,5.95,0,NaN,NaN
1,2012,1.0,1.0,Aachen,93.085192,7.40,7.16,8.69,6.21,1,NaN,NaN
2,2012,1.0,1.0,Augsburg,84.383804,7.00,7.00,7.62,6.33,0,NaN,NaN
3,2012,1.0,1.0,Augsburg,88.031743,7.31,7.30,7.95,6.61,1,NaN,NaN
4,2012,1.0,1.0,Berlin,83.126205,7.13,6.76,8.04,5.85,0,NaN,NaN
5,2012,1.0,1.0,Berlin,86.719778,7.44,7.05,8.39,6.10,1,NaN,NaN
6,2012,1.0,1.0,Bielefeld,92.340942,5.84,5.71,6.40,5.11,0,NaN,NaN
7,2012,1.0,1.0,Bielefeld,96.332871,6.09,5.96,6.68,5.33,1,NaN,NaN
8,2012,1.0,1.0,Bocholt,90.769547,5.81,5.42,6.58,5.23,0,NaN,NaN
9,2012,1.0,1.0,Bocholt,94.693543,6.06,5.65,6.86,5.46,1,NaN,NaN

In [7]:
df.shape

(18696, 12)

In [9]:
df.dtypes

Year                    int64
Quarter               float64
Month                 float64
City                   object
Index                 float64
AVG_PRICE_SQM         float64
MED_PRICE_SQM         float64
P75_PRICE_SQM         float64
P25_PRICE_SQM         float64
Inflation_adjusted      int64
TOM_4Q                float64
Closed_one_week_4Q    float64
dtype: object

In [15]:
df['City'].unique()

array(['Aachen', 'Augsburg', 'Berlin', 'Bielefeld', 'Bocholt', 'Bochum',
       'Bonn', 'Braunschweig', 'Bremen', 'Chemnitz', 'Dortmund',
       'Dresden', 'Duisburg', 'Düsseldorf', 'Erfurt', 'Essen',
       'Frankfurt am Main', 'Greix', 'Gelsenkirchen', 'Hamburg', 'Hamm',
       'Hannover', 'Karlsruhe', 'Kiel', 'Köln', 'Leipzig', 'Lübeck',
       'Mönchengladbach', 'Mannheim', 'Kreis Mettmann', 'München',
       'Münster', 'Nürnberg', 'Potsdam', 'Rhein-Erft-Kreis', 'Stuttgart',
       'Wiesbaden', 'Wuppertal'], dtype=object)

In [21]:
df['Year'].isna().sum()

0

In [23]:
df['Quarter'].isna().sum()

1064

In [25]:
df['Month'].isna().sum()

5472

In [27]:
((df['Quarter'].notna()) & (df['Month'].notna())).sum()

13224

In [29]:
((df['Quarter'].notna()) & (df['Month'].isna())).sum()

4408

In [31]:
((df['Quarter'].isna()) & (df['Month'].isna())).sum()

1064

In [35]:
df[(df['Quarter'].notna()) & (df['Month'].notna())].head()

,Year,Quarter,Month,City,Index,AVG_PRICE_SQM,MED_PRICE_SQM,P75_PRICE_SQM,P25_PRICE_SQM,Inflation_adjusted,TOM_4Q,Closed_one_week_4Q
0,2012,1.0,1.0,Aachen,89.227844,7.10,6.86,8.33,5.95,0,NaN,NaN
1,2012,1.0,1.0,Aachen,93.085192,7.40,7.16,8.69,6.21,1,NaN,NaN
2,2012,1.0,1.0,Augsburg,84.383804,7.00,7.00,7.62,6.33,0,NaN,NaN
3,2012,1.0,1.0,Augsburg,88.031743,7.31,7.30,7.95,6.61,1,NaN,NaN
4,2012,1.0,1.0,Berlin,83.126205,7.13,6.76,8.04,5.85,0,NaN,NaN

In [37]:
df[(df['Quarter'].notna()) & (df['Month'].isna())].head()

,Year,Quarter,Month,City,Index,AVG_PRICE_SQM,MED_PRICE_SQM,P75_PRICE_SQM,P25_PRICE_SQM,Inflation_adjusted,TOM_4Q,Closed_one_week_4Q
228,2012,1.0,NaN,Aachen,90.341499,7.26,7.00,8.43,6.00,0,NaN,NaN
229,2012,1.0,NaN,Aachen,93.661178,7.53,7.26,8.74,6.22,1,NaN,NaN
230,2012,1.0,NaN,Augsburg,84.544258,7.06,7.00,7.81,6.36,0,NaN,NaN
231,2012,1.0,NaN,Augsburg,87.650912,7.32,7.26,8.10,6.60,1,NaN,NaN
232,2012,1.0,NaN,Berlin,83.688828,7.18,6.86,8.14,5.90,0,NaN,NaN

In [39]:
df[(df['Quarter'].isna()) & (df['Month'].isna())].head()

,Year,Quarter,Month,City,Index,AVG_PRICE_SQM,MED_PRICE_SQM,P75_PRICE_SQM,P25_PRICE_SQM,Inflation_adjusted,TOM_4Q,Closed_one_week_4Q
1216,2012,NaN,NaN,Aachen,91.886055,7.26,7.01,8.29,6.00,0,NaN,NaN
1217,2012,NaN,NaN,Aachen,94.665422,7.48,7.23,8.54,6.18,1,NaN,NaN
1218,2012,NaN,NaN,Augsburg,85.166122,7.10,7.01,7.86,6.40,0,NaN,NaN
1219,2012,NaN,NaN,Augsburg,87.742226,7.32,7.23,8.09,6.59,1,NaN,NaN
1220,2012,NaN,NaN,Berlin,86.092232,7.45,7.06,8.50,6.05,0,NaN,NaN

In [41]:
def assign_granularity(row):
    if pd.notna(row['Month']):
        return "monthly"
    elif pd.notna(row['Quarter']):
        return "quarterly"
    else:
        return "annual"

In [45]:
df["Granularity"] = df.apply(assign_granularity, axis = 1)
df["Granularity"].value_counts()

Granularity
monthly      13224
quarterly     4408
annual        1064
Name: count, dtype: int64

In [54]:
df["City"] = df["City"].apply(canonical_city)

In [56]:
df["City"].unique()

array(['Aachen', 'Augsburg', 'Berlin', 'Bielefeld', 'Bocholt', 'Bochum',
       'Bonn', 'Braunschweig', 'Bremen', 'Chemnitz', 'Dortmund',
       'Dresden', 'Duisburg', 'Düsseldorf', 'Erfurt', 'Essen',
       'Frankfurt am Main', 'GREIX_NATIONAL', 'Gelsenkirchen', 'Hamburg',
       'Hamm', 'Hannover', 'Karlsruhe', 'Kiel', 'Köln', 'Leipzig',
       'Lübeck', 'Mönchengladbach', 'Mannheim', 'Kreis Mettmann',
       'München', 'Münster', 'Nürnberg', 'Potsdam', 'Rhein-Erft-Kreis',
       'Stuttgart', 'Wiesbaden', 'Wuppertal'], dtype=object)

In [62]:
df_city = df[df["City"]!= "GREIX_NATIONAL"].copy()
df_national = df[df["City"] == "GREIX_NATIONAL"].copy()

In [72]:
print(df_city.shape)
print(df_national.shape)

(18204, 13)
(492, 13)

In [80]:
df_city.to_csv("../data/clean/city_metrics_cities.csv", index = False)
df_national.to_csv("../data/clean/city_metrics_national.csv", index = False)

In [74]:
df_city.head()

,Year,Quarter,Month,City,Index,AVG_PRICE_SQM,MED_PRICE_SQM,P75_PRICE_SQM,P25_PRICE_SQM,Inflation_adjusted,TOM_4Q,Closed_one_week_4Q,Granularity
0,2012,1.0,1.0,Aachen,89.227844,7.10,6.86,8.33,5.95,0,NaN,NaN,monthly
1,2012,1.0,1.0,Aachen,93.085192,7.40,7.16,8.69,6.21,1,NaN,NaN,monthly
2,2012,1.0,1.0,Augsburg,84.383804,7.00,7.00,7.62,6.33,0,NaN,NaN,monthly
3,2012,1.0,1.0,Augsburg,88.031743,7.31,7.30,7.95,6.61,1,NaN,NaN,monthly
4,2012,1.0,1.0,Berlin,83.126205,7.13,6.76,8.04,5.85,0,NaN,NaN,monthly

In [84]:
df_city.duplicated().sum()

0

In [86]:
df_national.duplicated().sum()

0

In [90]:
print(df_city["TOM_4Q"].isna().sum())
print(df_city["Closed_one_week_4Q"].isna().sum())
print(df_city.shape[0])

14134
14134
18204

In [92]:
missing_tom = df_city[df_city["TOM_4Q"].isna()]
print(missing_tom['Year'].value_counts().sort_index())

Year
2012    1184
2013     962
2014     962
2015     962
2016     962
2017     962
2018     962
2019     962
2020     962
2021     962
2022     962
2023     962
2024     962
2025     962
2026     444
Name: count, dtype: int64

In [94]:
df_city.groupby("Granularity")['TOM_4Q'].apply(lambda x: x.isna().sum())

Granularity
annual        1036
monthly      12876
quarterly      222
Name: TOM_4Q, dtype: int64

In [96]:
leftover = df_city[(df_city["Granularity"] == "quarterly") & (df_city["TOM_4Q"].isna())]
print(leftover['Year'].value_counts().sort_index())

Year
2012    222
Name: count, dtype: int64

In [98]:
df_city.describe()

,Year,Quarter,Month,Index,AVG_PRICE_SQM,MED_PRICE_SQM,P75_PRICE_SQM,P25_PRICE_SQM,Inflation_adjusted,TOM_4Q,Closed_one_week_4Q
count,18204.000000,17168.000000,12876.000000,18204.000000,18204.000000,18204.000000,18204.000000,18204.000000,18204.000000,4070.000000,4070.000000
mean,2018.743902,2.465517,6.396552,110.689651,8.857457,8.648135,9.948935,7.559201,0.500000,32.110912,0.250194
std,4.182378,1.117535,3.450636,14.727511,2.669925,2.602170,3.142124,2.158449,0.500014,11.129455,0.103454
min,2012.000000,1.000000,1.000000,81.876022,4.640000,4.490000,4.910000,4.140000,0.000000,14.685730,0.039385
25%,2015.000000,1.000000,3.000000,100.000000,6.950000,6.800000,7.730000,6.010000,0.000000,24.283530,0.173121
50%,2019.000000,2.000000,6.000000,107.427056,8.420000,8.240000,9.440000,7.190000,0.500000,29.818637,0.243128
75%,2022.000000,3.000000,9.000000,116.241974,10.200000,9.990000,11.490000,8.650000,1.000000,36.957184,0.316827
max,2026.000000,4.000000,12.000000,170.657532,23.810000,23.230000,27.020000,20.110000,1.000000,76.175848,0.593398

In [100]:
df_city[['AVG_PRICE_SQM', 'MED_PRICE_SQM', 'P75_PRICE_SQM', 'P25_PRICE_SQM']].describe()

       AVG_PRICE_SQM  MED_PRICE_SQM  P75_PRICE_SQM  P25_PRICE_SQM
count   18204.000000   18204.000000   18204.000000   18204.000000
mean        8.857457       8.648135       9.948935       7.559201
std         2.669925       2.602170       3.142124       2.158449
min         4.640000       4.490000       4.910000       4.140000
25%         6.950000       6.800000       7.730000       6.010000
50%         8.420000       8.240000       9.440000       7.190000
75%        10.200000       9.990000      11.490000       8.650000
max        23.810000      23.230000      27.020000      20.110000

In [104]:
df_city.loc[df_city['P75_PRICE_SQM'].idxmax(), ['City', 'Year', 'Quarter', 'Month', 'P75_PRICE_SQM']]

City             München
Year                2026
Quarter              1.0
Month                3.0
P75_PRICE_SQM      27.02
Name: 18300, dtype: object