In [1]:
import sys
sys.path.append("../src")

import pandas as pd
from city_mapping import canonical_city, GREIX_NATIONAL

In [2]:
df2 = pd.read_excel("../data/raw/greix/City_Metrics_rents_sales-Mietpreis-Transaktionspreisindex.xlsx", sheet_name = "Sheet1")
df2.head(10)

   Year  Quarter      City  Rent_Index  Sales_Index  Inflation_adjusted
0  2012      1.0    Berlin   83.688828    72.275360                   0
1  2012      1.0    Berlin   86.764048    74.880325                   1
2  2012      1.0      Bonn   92.828407    82.165977                   0
3  2012      1.0      Bonn   96.239469    85.107773                   1
4  2012      1.0  Dortmund   91.366402    88.293068                   0
5  2012      1.0  Dortmund   94.723741    91.474152                   1
6  2012      1.0   Dresden   87.872002    82.020119                   0
7  2012      1.0   Dresden   91.100936    84.978790                   1
8  2012      1.0  Duisburg   94.829552   114.213387                   0
9  2012      1.0  Duisburg   98.314148   118.307823                   1

In [3]:
df2.shape

(2838, 6)

In [4]:
df2.dtypes

Year                    int64
Quarter               float64
City                   object
Rent_Index            float64
Sales_Index           float64
Inflation_adjusted      int64
dtype: object

In [5]:
df2["Quarter"].isna().sum()

594

In [6]:
def assign_granularity_2(row):
    if pd.notna(row['Quarter']):
        return "quarterly"
    else:
        return "annual"

In [7]:
df2["Granularity"] = df2.apply(assign_granularity_2, axis =1)
df2['Granularity'].value_counts()

Granularity
quarterly    2244
annual        594
Name: count, dtype: int64

In [8]:
df2['City'].unique()

array(['Berlin', 'Bonn', 'Dortmund', 'Dresden', 'Duisburg', 'Düsseldorf',
       'Erfurt', 'Frankfurt am Main', 'Greix', 'Hamburg', 'Karlsruhe',
       'Köln', 'Lübeck', 'Mettmann_kreis', 'München', 'Münster',
       'Potsdam', 'Rhein-Erft-Kreis', 'Stuttgart', 'Wiesbaden', 'Bocholt',
       'Chemnitz', 'Leipzig'], dtype=object)

In [9]:
df2['City'] = df2['City'].apply(canonical_city)

In [10]:
df2['City'].unique()

array(['Berlin', 'Bonn', 'Dortmund', 'Dresden', 'Duisburg', 'Düsseldorf',
       'Erfurt', 'Frankfurt am Main', 'GREIX_NATIONAL', 'Hamburg',
       'Karlsruhe', 'Köln', 'Lübeck', 'Kreis Mettmann', 'München',
       'Münster', 'Potsdam', 'Rhein-Erft-Kreis', 'Stuttgart', 'Wiesbaden',
       'Bocholt', 'Chemnitz', 'Leipzig'], dtype=object)

In [22]:
df2.duplicated().sum()

0

In [24]:
df2_city = df2[df2["City"]!= "GREIX_NATIONAL"].copy()
df2_national = df2[df2["City"] == "GREIX_NATIONAL"].copy()

In [26]:
print(df2_city.shape)
print(df2_national.shape)

(2704, 7)
(134, 7)

In [28]:
df2_city[['Rent_Index','Sales_Index']].isna().sum()

Rent_Index     0
Sales_Index    0
dtype: int64

In [30]:
df2_city[['Rent_Index','Sales_Index']].describe()

        Rent_Index  Sales_Index
count  2704.000000  2704.000000
mean    109.563657   131.518937
std      13.098466    34.689055
min      83.688828    69.808937
25%     100.000000   100.424292
50%     106.927865   127.676121
75%     115.491632   158.581429
max     165.480881   241.083313

In [40]:
df2_city[(df2_city['Year'] == 2025) & df2_city['Quarter'] == 1][['City','Rent_Index','Sales_Index']].head(10)

          City  Rent_Index  Sales_Index
2762    Berlin  163.944382   205.788208
2763    Berlin  128.309217   161.636124
2764      Bonn  141.234482   190.042374
2765      Bonn  110.535571   149.234131
2766  Dortmund  148.370071   188.808228
2767  Dortmund  116.120159   148.297287
2768   Dresden  135.123306   178.595108
2769   Dresden  105.752728   140.281433
2770  Duisburg  146.149734   206.529785
2771  Duisburg  114.382438   162.188339

In [42]:
df2_city.to_csv("../data/clean/rents_sales_cities.csv", index = False)
df2_national.to_csv("../data/clean/rents_sales_national.csv", index = False)